wav2kcc:    src/main.cpp src/kc85handler.cpp src/turbo4handler.cpp src/handler.cpp
	g++  -g -Wall -pedantic -std=c++11 -Werror -Ih -o wav2kcc src/main.cpp src/kc85handler.cpp src/handler.cpp src/turbo4handler.cpp 

clean:
	rm -f wav2kcc

